bugbyte/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path("__debug__/", include('debug_toolbar.urls', namespace='debug_toolbar')),
] + debug_toolbar_urls()
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path('', views.index, name='index'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models.functions import Lower


# Create your models here.
# Restaurant Management System.

class Restaurant(models.Model):
  class TypeChoices(models.TextChoices):
    INDIAN = 'IN', 'Indian'
    CHINESE = 'CH', 'Chinese'
    ITALIAN = 'IT', 'Italian'
    GREEK = 'GR', 'Greek'
    MEXICAN = 'MX', 'Mexican'
    FASTFOOD = 'FF', 'Fast Food'
    OTHER = 'OT', 'Other'

  name = models.CharField(max_length=100)
  website = models.URLField(default='')
  date_opened = models.DateField()
  latitude = models.FloatField(validators=[MinValueValidator(-90), MaxValueValidator(90)])
  longitude = models.FloatField(validators=[MinValueValidator(-180), MaxValueValidator(180)])
  restaurant_type = models.CharField(max_length=2, choices=TypeChoices.choices)

  class Meta:
    ordering = [Lower('name')]
    get_latest_by = 'date_opened'

  def __str__(self):
    return self.name
  
  def save(self, *args, **kwargs):
    print(self._state.adding)
    super().save(*args, **kwargs)

class Staff(models.Model):
  name = models.CharField(max_length=128)
  restaurants = models.ManyToManyField(Restaurant)
  
class Rating(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='ratings')
  rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

  def __str__(self):
    return f"Rating: {self.rating}"

class Sale(models.Model):
  restaurant = models.ForeignKey(Restaurant, on_delete=models.SET_NULL, null=True, related_name='sales')
  income = models.DecimalField(max_digits=8, decimal_places=2)
  datetime = models.DateTimeField()

core/views.py
from django.shortcuts import render
from core.models import Restaurant, Rating, Sale
from django.db.models import Sum, Prefetch
from django.utils import timezone

# Create your views here.
def index(request):
  month_ago = timezone.now() - timezone.timedelta(days=30)
  monthly_sales = Prefetch(
    'sales', # lookup
    queryset=Sale.objects.filter(datetime__gte=month_ago) # queryset
  )
  restaurants = Restaurant.objects.prefetch_related('ratings', monthly_sales).filter(ratings__rating=5)
  restaurants = restaurants.annotate(total=Sum('sales__income'))
  # restaurants = Restaurant.objects.prefetch_related('ratings', 'sales')\
  #   .filter(ratings__rating=5)\
  #   .annotate(total=Sum('sales__income'))
  # ratings = Rating.objects.only('rating', 'restaurant__name').select_related('restaurant')
  # context = {'ratings': ratings}
  # restaurants = Restaurant.objects.filter(name__istartswith='p').prefetch_related("ratings", "sales")
  print(restaurants)
  print([r.total for r in restaurants])
  context = {'restaurants': restaurants}
  return render(request, "core/index.html", context)

core/templates/core/index.html
{% extends 'layout.html' %}
{% block title %}
Core App
{% endblock %}
{% block content %}
{% comment %} 
  {% for rating in ratings %}
    <p>
      {{rating.restaurant.name}} - {{rating}}
    </p>
  {% endfor %} {% endcomment %}
  {% comment %} {% for restaurant in restaurants %}  
    <p>
      {{restaurant.name}}
    </p>
    Rating
    <ul>
      
      {% for rating in restaurant.ratings.all %}
        <li>
          {{rating.rating}}
        </li>  
      {% endfor %}
    </ul>

    Income
    <ul>
      
      {% for sale in restaurant.sales.all %}
        <li>
          {{sale.income}}
        </li>  
      {% endfor %}
    </ul>
  {% endfor %} {% endcomment %}
{% endblock %}

templates/about.html
{% extends 'layout.html' %}
{% block title %}
About Page
{% endblock %}
{% block content %}
  <h1>About Page</h1>
  <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% block title %}
Home
{% endblock %}
{% block content %}
  <h1>Home</h1>
  <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
      Django App.
    {% endblock %}
  </title>
  <script src="{% static 'js/main.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <nav>
    <a href="{% url 'core:index' %}">🏠</a> |
    </nav>
  <main>
    {% block content %}
    {% endblock %}
  </main> 
</body>
</html>